[package]
name = "kernel_os"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9"

[[bin]]
name = "kernel_os"
test = false
bench = false