[package]
name = "kernel_os"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9.23"
x86_64 = "0.14.10"
volatile = "0.2.6"
spin = "0.9.8"
lazy_static = { version = "1.4", features = ["spin_no_std"] }


[build-dependencies]
bootimage = "0.10.2"

